import { useEffect, useState } from "react";
import axios from "axios";

type Medicine = {
  _id: string;
  name: string;
  category: string;
  price: number;
  stock: number;
};

const API_URL = "http://localhost:5000/api/medicines";

interface MedicineListProps {
  onEdit: (id: string) => void;
  refresh: number; // parent can trigger reload
}

const MedicineList = ({ onEdit, refresh }: MedicineListProps) => {
  const [medicines, setMedicines] = useState<Medicine[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchMedicines = async () => {
    try {
      setLoading(true);
      const res = await axios.get(API_URL);
      setMedicines(res.data);
    } catch (err) {
      console.error("❌ Failed to fetch medicines:", err);
    } finally {
      setLoading(false);
    }
  };

  const deleteMedicine = async (id: string) => {
    if (!confirm("Are you sure you want to delete this medicine?")) return;
    try {
      await axios.delete(`${API_URL}/${id}`);
      fetchMedicines();
    } catch (err) {
      console.error("❌ Failed to delete medicine:", err);
    }
  };

  const generateInvoice = (medicine: Medicine) => {
    const invoiceWindow = window.open("", "_blank");
    if (!invoiceWindow) return;

    const date = new Date().toLocaleString();
    invoiceWindow.document.write(`
      <html>
        <head>
          <title>Invoice - ${medicine.name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #333; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background: #f4f4f4; }
            .footer { margin-top: 20px; font-size: 12px; color: #777; }
          </style>
        </head>
        <body>
          <h1>Medicine Invoice</h1>
          <p><strong>Date:</strong> ${date}</p>
          <table>
            <tr><th>Field</th><th>Details</th></tr>
            <tr><td>Name</td><td>${medicine.name}</td></tr>
            <tr><td>Category</td><td>${medicine.category}</td></tr>
            <tr><td>Price</td><td>$${medicine.price}</td></tr>
            <tr><td>Stock</td><td>${medicine.stock}</td></tr>
          </table>
          <div class="footer">
            <p>Generated by Medicine Inventory System</p>
          </div>
          <script>
            window.print();
          </script>
        </body>
      </html>
    `);
    invoiceWindow.document.close();
  };

  useEffect(() => {
    fetchMedicines();
  }, [refresh]);

  if (loading) return <p>Loading medicines...</p>;

  return (
    <div>
      <h2 className="text-xl font-bold mb-4">Medicine Inventory</h2>
      <table className="min-w-full bg-white shadow rounded-lg">
        <thead>
          <tr className="bg-gray-200 text-gray-700">
            <th className="py-2 px-4">SI.NO</th>
            <th className="py-2 px-4">Name</th>
            <th className="py-2 px-4">Category</th>
            <th className="py-2 px-4">Price</th>
            <th className="py-2 px-4">Stock</th>
            <th className="py-2 px-4">Actions</th>
          </tr>
        </thead>
        <tbody>
          {medicines.map((m, index) => (
            <tr key={m._id} className="border-t">
              <td className="py-2 px-4">{index + 1}</td>
              <td className="py-2 px-4">{m.name}</td>
              <td className="py-2 px-4">{m.category}</td>
              <td className="py-2 px-4">${m.price}</td>
              <td className="py-2 px-4">{m.stock}</td>
              <td className="py-2 px-4 space-x-2">
                <button
                  onClick={() => onEdit(m._id)}
                  className="bg-blue-500 text-white px-3 py-1 rounded"
                >
                  Edit
                </button>
                <button
                  onClick={() => deleteMedicine(m._id)}
                  className="bg-red-500 text-white px-3 py-1 rounded"
                >
                  Delete
                </button>
                <button
                  onClick={() => generateInvoice(m)}
                  className="bg-green-500 text-white px-3 py-1 rounded"
                >
                  Invoice
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default MedicineList;
